### ISSUE TITLE
TypeError: s.includes is not a function

### ISSUE THREAD

**Issue by Steve-Mcl** [StoneCypher/csv_by_rfc#24]
When running the example in the ts source, I get an error `TypeError: s.includes is not a function`

```
const data = [ ['ace', 'deuce', 'tres'], [1, 2, 3] ],
csv  = to_csv(data)
```

The reason is because numbers do not have an `includes` function.

And while typescript is specifying type `string` on the `quote_when_contains` signature, there is nothing stopping the `data` elements containing numbers.  In short, there is no runtime checking. 

![image](https://github.com/StoneCypher/csv_by_rfc/assets/44235289/f90e2c14-bc80-4678-b81d-620ef572fcf8)

```
Uncaught TypeError: s.includes is not a function
    at C:\Users\Stephen\.node-red\node_modules\csv_by_rfc\dist\to_csv.js:36:44
    at Array.some (<anonymous>)
    at quote_when_contains (C:\Users\Stephen\.node-red\node_modules\csv_by_rfc\dist\to_csv.js:36:30)
    at quote_minimal (C:\Users\Stephen\.node-red\node_modules\csv_by_rfc\dist\to_csv.js:65:12)
    at C:\Users\Stephen\.node-red\node_modules\csv_by_rfc\dist\to_csv.js:117:31
    at Array.map (<anonymous>)
    at stringify_make_row (C:\Users\Stephen\.node-red\node_modules\csv_by_rfc\dist\to_csv.js:117:20)
```

**Comment by StoneCypher** [comment]
yeah, this is very old code that i no longer agree with

i'll fix this promptly
